import { useEffect, useState } from 'react';
import { api } from '../api/client.js';

export default function SettingsView({ dashboard, setDashboard, timings, setTimings, toast }) {
  const [dashboardForm, setDashboardForm] = useState(dashboard || { courseLabel: '', sessionLabel: '', yearLabel: '', semesterLabel: '' });
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setDashboardForm(dashboard || { courseLabel: '', sessionLabel: '', yearLabel: '', semesterLabel: '' });
  }, [dashboard]);
  const sessionInput = (key, label, placeholder) => <label>{label}<input value={dashboardForm[key] || ''} onChange={(event) => setDashboardForm((value) => ({ ...value, [key]: event.target.value }))} placeholder={placeholder} required /></label>;
  async function saveSession(event) { event.preventDefault(); setSaving(true); try { const saved = await api.saveDashboardSettings(dashboardForm); setDashboard(saved); toast('Dashboard session details saved.'); } catch (error) { toast(error.message); } finally { setSaving(false); } }
  async function saveTiming(event, course) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const saved = await api.saveAttendanceSettings({ course, ...data }); setTimings((rows) => rows.map((row) => row.course === course ? saved : row)); toast(`Timing saved for ${course}.`); } catch (error) { toast(error.message); } }
  return <section><div className="page-heading"><div><p className="eyebrow">TEACHER CONTROLS</p><h2>Class settings</h2><p className="muted">Manage dashboard session information and attendance timing rules for your classes.</p></div></div><section className="dashboard-session-card"><div><p className="eyebrow">MAIN DASHBOARD</p><h3>Session information</h3><p>Choose the course, academic session, year and semester shown in your dashboard session card.</p></div><form className="dashboard-session-form" onSubmit={saveSession}>{sessionInput('courseLabel', 'Course', 'e.g. BCA')}{sessionInput('sessionLabel', 'Academic session', 'e.g. 2026-27')}{sessionInput('yearLabel', 'Year', 'e.g. Third Year')}{sessionInput('semesterLabel', 'Semester', 'e.g. Semester 5')}<button className="primary-btn" disabled={saving}>{saving ? 'Saving…' : 'Save session'}</button></form></section><section className="settings-info"><strong>How attendance is calculated</strong><span>Before start: rejected</span><span>Start to Present Until: Present</span><span>Present Until to End: Late</span><span>After end: rejected</span></section><div className="settings-list">{timings.length ? timings.map((setting) => <form className="class-setting-card" key={setting.course} onSubmit={(event) => saveTiming(event, setting.course)}><div className="class-setting-course"><h3>Class attendance timing</h3><p>{setting.course} · QR scans for this class follow the timing window below.</p></div><label>Attendance Start<input type="time" name="startTime" defaultValue={setting.startTime || ''} required /></label><label>Present Until<input type="time" name="presentUntil" defaultValue={setting.presentUntil || ''} required /></label><label>Attendance End<input type="time" name="endTime" defaultValue={setting.endTime || ''} required /></label><button className="primary-btn">Save timings</button></form>) : <div className="setting-empty"><span>◷</span><h3>No classes yet</h3><p>Add a student first. Their course will appear here for timing setup.</p></div>}</div></section>;
}
